
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:

title: Mudrika's Page 
description: edit your description in /docs/_config.yml

theme: jekyll-theme-minimal
